# -*- coding: utf-8 -*-
"""python-budget-tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10D9IhZA6E2LWrq8sKCZUTWcrpWtGBVyB
"""

import csv
import os

FILENAME = 'transactions.csv'

# Load existing transactions from CSV
def load_transactions():
    transactions = []
    if os.path.exists(FILENAME):
        with open(FILENAME, mode='r', newline='') as file:
            reader = csv.DictReader(file)
            for row in reader:
                row['amount'] = float(row['amount'])
                transactions.append(row)
    return transactions

# Save transactions to CSV
def save_transactions(transactions):
    with open(FILENAME, mode='w', newline='') as file:
        fieldnames = ['type', 'description', 'amount']
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for txn in transactions:
            writer.writerow(txn)

# Add income or expense
def add_transaction(transactions, txn_type):
    desc = input("Enter description: ")
    while True:
        try:
            amount = float(input("Enter amount: "))
            if amount <= 0:
                raise ValueError
            break
        except ValueError:
            print("Please enter a valid positive number.")

    if txn_type == 'expense':
        amount = -amount  # Expenses are negative

    transactions.append({
        'type': txn_type,
        'description': desc,
        'amount': amount
    })
    save_transactions(transactions)
    print(f"{txn_type.capitalize()} added successfully!\n")

# Show balance
def show_balance(transactions):
    balance = sum(txn['amount'] for txn in transactions)
    print(f"\nCurrent Balance: ₹{balance:.2f}\n")

# Show all transactions
def show_history(transactions):
    if not transactions:
        print("No transactions found.")
        return
    print("\n--- Transaction History ---")
    for txn in transactions:
        print(f"{txn['type'].capitalize():<8} | {txn['description']:<20} | ₹{txn['amount']:.2f}")
    print()

# Main program loop
def main():
    transactions = load_transactions()

    while True:
        print("=== Budget Tracker ===")
        print("1. Add Income")
        print("2. Add Expense")
        print("3. View Balance")
        print("4. View Transaction History")
        print("5. Exit")

        choice = input("Choose an option (1-5): ")
        print()

        if choice == '1':
            add_transaction(transactions, 'income')
        elif choice == '2':
            add_transaction(transactions, 'expense')
        elif choice == '3':
            show_balance(transactions)
        elif choice == '4':
            show_history(transactions)
        elif choice == '5':
            print("Goodbye!")
            break
        else:
            print("Invalid choice. Try again.\n")

if __name__ == '__main__':
    main()